# Generated by Django 4.2.7 on 2024-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
