# Generated by Django 4.2.7 on 2024-04-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.IntegerField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateField(auto_now_add=True)),
                ('deliveryAddress', models.TextField(max_length=100)),
                ('deliveryDate', models.DateField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
